### PR TITLE
Standalone sbot (installer work)

### PR DESCRIPTION
**Pull request by mixmix**
from work Matt did : 

What's working
- can build installers on mac (probably on other platforms too, but haven't tested)
- sbot is bundled running on a custom port (43750, and blobs on 43751)

not working
- the app... not sure why not but I don't have time to figure this out right now. When I first cloned it down and ran it against my local sbot, I was seeing posts, but now when I try it, just does't work. shrugs

### CODE REVIEW

**Comment by mixmix** [comment]
I'm smoketesting this now

**Comment by mixmix** [comment]
This looks legit. Have added notes to this repo and the build one.
If we merge this, we're going to have to start over-riding the default `ssb_appname` ... and I think this setup is building some other indexes (just judging by the console output)

**Comment by mixmix** [comment]
@dominictarr I think this is good to merge.
I think the only thing I'd like you to check whether there are any suspect ssb modules we're pulling in.

**Comment by dominictarr** [comment]
the appname should not have "-" in it because that breaks `rc` env vars

**Comment by dominictarr** [comment]
I will change it to just "ticktack"

**Comment by dominictarr** [comment]
how did you get this to work?

**Comment by dominictarr** [comment]
I think long term, this is the wrong way to approach making ssb apps. building electron in is gonna make it harder to build on other platforms, but this is the way we have for now. so this is merged.

**Pull request merged**
