### PR TITLE
homescreen - box model + mcss work

### PR DESCRIPTION
**Pull request by mixmix**
This is a first pass on styling. It makes the interface functional and starts to surface questions about the design.

selection_359

Adds:
- styling to the home screen
  - visual groupings
  - seperate **'context'** (channel, people in thead, group) from **'content'** (subject + reply)
- extends firstLine sampling so it doesn't break md links
  - printing split markdown (e.g.` "...here is that [youtube video](https://w"`  )  looks terrible : 
  - _this is a bit of a pain, and probably needs more work in future_

Note that the way the thread chunks are set up, you can't actually click links because of the click-handler at the moment

### CODE REVIEW

**Comment by dominictarr** [comment]
2 thoughts:
* if you use a centered column it will lead you towards designs that will also work on mobile.
* index screens should be visually distinct from conversations, for example: square instead of rounded

**Comment by mixmix** [comment]
I looked at kik and update a little. will read and reply to your comment in a moment 

selection_360

**Comment by mixmix** [comment]
agree on the style thing re square. I'll nock it back heaps. 
It is actually a column, I'll make everything line up - wasn't sure how edges should look because conversation are so dynamic.

I notice that I could do a lot of fiddling with styles, but this is dangerous when it comes to modifying box model - it gets expensive to rework. I'm keen to get it kind of close to useable and ok then come back

**Comment by mixmix** [comment]
selection_361

@dominictarr ready for smoke test + code review

**Comment by mixmix** [comment]
@dominictarr I notice that the this homepage isn't updating my view of private messages - not sure if that's expected. (e.g. I sent a new private message in that "exciting updates thread" with marco, but it's not showing up)

**Comment by dominictarr** [comment]
this is probably good enough for now, to look really really good you wanna fix the avatars into the same square, like join them with a slash or something? maybe wrap the channel names to fit too?

but I reckon leave that till other stuff is working.

**Comment by dominictarr** [comment]
I've merged this into my `homescreen` branch. it was kinda a pain so please please pull my branch if you work on this again.

**Comment by mixmix** [comment]
Ok I'll merge this into master and leave the homescreen alone till that other branch is done.

**Comment by dominictarr** [comment]
okay, I just merged this into my homescreen, so it ought to be easy to merge with master later

**Pull request merged**
